mkdir -p ~/output/baseline/swan/BigBench
mkdir -p ~/output/baseline/swan/FB
mkdir -p ~/output/baseline/swan/TPC-DS
mkdir -p ~/output/baseline/swan/TPC-H
mkdir -p ~/output/baseline/gb4/BigBench
mkdir -p ~/output/baseline/gb4/FB
mkdir -p ~/output/baseline/gb4/TPC-DS
mkdir -p ~/output/baseline/gb4/TPC-H
mkdir -p ~/output/baseline/ntt_new/BigBench
mkdir -p ~/output/baseline/ntt_new/FB
mkdir -p ~/output/baseline/ntt_new/TPC-DS
mkdir -p ~/output/baseline/ntt_new/TPC-H
mkdir -p ~/output/baseline/AttMpls/BigBench
mkdir -p ~/output/baseline/AttMpls/FB
mkdir -p ~/output/baseline/AttMpls/TPC-DS
mkdir -p ~/output/baseline/AttMpls/TPC-H
mkdir -p ~/output/recursive-remain-flow/swan/BigBench
mkdir -p ~/output/recursive-remain-flow/swan/FB
mkdir -p ~/output/recursive-remain-flow/swan/TPC-DS
mkdir -p ~/output/recursive-remain-flow/swan/TPC-H
mkdir -p ~/output/recursive-remain-flow/gb4/BigBench
mkdir -p ~/output/recursive-remain-flow/gb4/FB
mkdir -p ~/output/recursive-remain-flow/gb4/TPC-DS
mkdir -p ~/output/recursive-remain-flow/gb4/TPC-H
mkdir -p ~/output/recursive-remain-flow/ntt_new/BigBench
mkdir -p ~/output/recursive-remain-flow/ntt_new/FB
mkdir -p ~/output/recursive-remain-flow/ntt_new/TPC-DS
mkdir -p ~/output/recursive-remain-flow/ntt_new/TPC-H
mkdir -p ~/output/recursive-remain-flow/AttMpls/BigBench
mkdir -p ~/output/recursive-remain-flow/AttMpls/FB
mkdir -p ~/output/recursive-remain-flow/AttMpls/TPC-DS
mkdir -p ~/output/recursive-remain-flow/AttMpls/TPC-H
