#!/usr/bin/env python

import pandas as pd
import numpy as np
import sys


def main():

    data = pd.read_csv(sys.argv[1])

    jct = data[ data.columns[3] ]
    jct = jct[jct>0]
    print (jct.quantile(0.95)),


if __name__ == '__main__':
    main()
